AGREEMENT_LIST_INFO_DATA = {
    "filters": [
        {
            "type": "autocomplete",
            "field_name": "property",
            "parameter_name": "property",
            "disabled_by_default": False,
            "title": "Property",
            "app_name": "real_estate",
            "model_name": "property",
        },
        {
            "type": "autocomplete",
            "field_name": "project",
            "parameter_name": "project",
            "disabled_by_default": False,
            "title": "Project",
            "app_name": "real_estate",
            "model_name": "project",
        },
        {
            "choices": [{"d": " - ", "v": None}],
            "disabled_by_default": False,
            "field_name": "description",
            "input_max": None,
            "input_min": None,
            "input_type": "text",
            "parameter_name": "description",
            "placeholder": "",
            "step": None,
            "title": "Description",
            "type": "str",
        },
        {
            "type": "int",
            "field_name": "property_construction_year__min",
            "parameter_name": "property_construction_year__min",
            "disabled_by_default": False,
            "title": "Property construction year Minimum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "number",
            "input_min": None,
            "input_max": None,
            "step": 1,
            "placeholder": "",
        },
        {
            "type": "int",
            "field_name": "property_construction_year__max",
            "parameter_name": "property_construction_year__max",
            "disabled_by_default": False,
            "title": "Property construction year Maximum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "number",
            "input_min": None,
            "input_max": None,
            "step": 1,
            "placeholder": "",
        },
        {
            "type": "choice",
            "field_name": "type",
            "parameter_name": "type",
            "disabled_by_default": False,
            "title": "type",
            "choices": [
                {"d": " - ", "v": None},
                {"d": "Contract of Sale", "v": "COS"},
                {"d": "Tenancy Agreement", "v": "TEN"},
                {"d": "Property management Agreement", "v": "PMG"},
            ],
        },
        {
            "type": "choice",
            "field_name": "status",
            "parameter_name": "status",
            "disabled_by_default": False,
            "title": "status",
            "choices": [
                {"d": " - ", "v": None},
                {"d": "Open", "v": "OPN"},
                {"d": "Reserved", "v": "RSV"},
                {"d": "Cancelled", "v": "CNL"},
                {"d": "Agreed", "v": "AGR"},
            ],
        },
        {
            "type": "datetime",
            "field_name": "created_at__min",
            "parameter_name": "created_at__min",
            "disabled_by_default": False,
            "title": "Created at Minimum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "datetime-local",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "datetime",
            "field_name": "created_at__max",
            "parameter_name": "created_at__max",
            "disabled_by_default": False,
            "title": "Created at Maximum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "datetime-local",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "choices": [{"d": " - ", "v": None}],
            "disabled_by_default": False,
            "field_name": "agreement_int__min",
            "input_max": None,
            "input_min": None,
            "input_type": "number",
            "parameter_name": "agreement_int__min",
            "placeholder": "",
            "step": 1,
            "title": "Agreement int Minimum",
            "type": "int",
        },
        {
            "choices": [{"d": " - ", "v": None}],
            "disabled_by_default": False,
            "field_name": "agreement_int__max",
            "input_max": None,
            "input_min": None,
            "input_type": "number",
            "parameter_name": "agreement_int__max",
            "placeholder": "",
            "step": 1,
            "title": "Agreement int Maximum",
            "type": "int",
        },
        {
            "type": "date",
            "field_name": "reservation_date__min",
            "parameter_name": "reservation_date__min",
            "disabled_by_default": False,
            "title": "Reservation date Minimum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "date",
            "field_name": "reservation_date__max",
            "parameter_name": "reservation_date__max",
            "disabled_by_default": False,
            "title": "Reservation date Maximum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "date",
            "field_name": "agreement_signing_date__min",
            "parameter_name": "agreement_signing_date__min",
            "disabled_by_default": False,
            "title": "Signing date Minimum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "date",
            "field_name": "agreement_signing_date__max",
            "parameter_name": "agreement_signing_date__max",
            "disabled_by_default": False,
            "title": "Signing date Maximum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "date",
            "field_name": "cancel_date__min",
            "parameter_name": "cancel_date__min",
            "disabled_by_default": False,
            "title": "Cancel date Minimum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "date",
            "field_name": "cancel_date__max",
            "parameter_name": "cancel_date__max",
            "disabled_by_default": False,
            "title": "Cancel date Maximum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "float",
            "field_name": "price__min",
            "parameter_name": "price__min",
            "disabled_by_default": False,
            "title": "Price Minimum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "number",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "float",
            "field_name": "price__max",
            "parameter_name": "price__max",
            "disabled_by_default": False,
            "title": "Price Maximum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "number",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "date",
            "field_name": "valid_from__min",
            "parameter_name": "valid_from__min",
            "disabled_by_default": False,
            "title": "Valid from Minimum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "date",
            "field_name": "valid_from__max",
            "parameter_name": "valid_from__max",
            "disabled_by_default": False,
            "title": "Valid from Maximum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "date",
            "field_name": "valid_until__min",
            "parameter_name": "valid_until__min",
            "disabled_by_default": False,
            "title": "Valid until Minimum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
        {
            "type": "date",
            "field_name": "valid_until__max",
            "parameter_name": "valid_until__max",
            "disabled_by_default": False,
            "title": "Valid until Maximum",
            "choices": [{"d": " - ", "v": None}],
            "input_type": "date",
            "input_min": None,
            "input_max": None,
            "step": None,
            "placeholder": "",
        },
    ],
    "actions": [
        ("", "---------"),
        ("delete_selected", "Delete selected agreements"),
        ("test_action", "Test action"),
    ],
    "extra_data": {"data": "extra data"},
    "list_max_show_all": 20,
    "sortable_by": [
        "created_at",
        "agreement_signing_date",
        "property",
        "valid_from",
        "reservation_date",
        "price",
    ],
}


def get_serialized_agreement_data(agreement):
    return {
        "id": agreement.id,
        "status": agreement.get_status_display(),
        "type": agreement.get_type_display(),
        "created_at": agreement.created_at.strftime("%d/%m/%Y - %H:%M"),
        "updated_at": agreement.updated_at.strftime("%d/%m/%Y - %H:%M"),
        "reservation_date": agreement.reservation_date.strftime("%d/%m/%Y")
        if agreement.reservation_date
        else None,
        "assigned_to": str(agreement.assigned_to) if agreement.assigned_to else None,
        "project": str(agreement.project) if agreement.project else None,
        "property": str(agreement.property) if agreement.property else None,
        "valid_from": agreement.valid_from.strftime("%d/%m/%Y")
        if agreement.valid_from
        else None,
        "valid_until": agreement.valid_until.strftime("%d/%m/%Y")
        if agreement.valid_until
        else None,
        "cancel_date": agreement.cancel_date.strftime("%d/%m/%Y")
        if agreement.cancel_date
        else None,
        "pk": agreement.pk,
    }
